name: era_datetime
description: "Era DateTime is a Library for handling date and time in different chronology in grogorian calendar."
version: 0.0.1
homepage: https://github.com/b2nkuu/d2rt-project
repository: https://github.com/b2nkuu/d2rt-project/tree/main/era_datetime

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter 
  intl: ^0.20.0 
  
dev_dependencies:
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
