include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: info

linter:
  rules:
    # Style rules
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_empty_else
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - package_names
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - sized_box_for_whitespace
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - use_key_in_widget_constructors
    - use_named_constants
