name: era_datetime_example
description: "Demonstrates how to use the era_datetime plugin."
publish_to: "none"

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  era_datetime:
    path: ../
  flutter:
    sdk: flutter
  intl: ^0.20.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
